version: '3.7'

services:
  postgres:
    image: postgres:12.2-alpine
    env_file: postgres.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata_todos:/var/lib/postgresql/data

  adminer:
    image: dehy/adminer
    links:
      - postgres
    ports:
      - "8888:80"

volumes:
    pgdata_todos: